### ISSUE TITLE
Good Work

### ISSUE THREAD

**Issue by okiyitooo** [mp1pro/jamming#6]
@mp1pro Good day,

However this may reach you, it is a security risk to upload your client id on github.

Your code was however spectacular, Good Work.

**Comment by mp1pro** [comment]
Thanks for the warning @okiyitooo. I will remove it today. thanks

**Comment by okiyitooo** [comment]
No problem, 
I hope this finds you well.

**Comment by mp1pro** [comment]
Private key removed, as per security threat. closes #6
